Repository imi-frankfurt/dataelementhub.gui, pull requests merged in 2022-07, with the labels that each got.

#60 remove /auth from keycloak url
  nuxt.config.js
Labels: refactoring

#65 #64 - Add slots table to dataElementGroup detail view
  components/views/groups-records-detail-view.vue
Labels: feature, needs review

#67 #66 - Public namespaces are saved as hidden
  assets/js/common.js
  components/dialogs/namespace-dialog.vue
  locales/de-DE.js
  locales/en-US.js
Labels: bug, needs review

#63 #62 - Auto release valueDomain with its associated dataElement
  assets/js/common.js
  components/dialogs/data-element-dialog.vue
Labels: needs review, refactoring

#55 #53 - secure cookies
  nuxt.config.js
Labels: needs review, refactoring

#73 #72 - Handle invalid token
  layouts/default.vue
  nuxt.config.js
  plugins/axios.js
Labels: needs review, refactoring
